name: Check VLESS Latency

on:
  schedule:
    - cron: '*/2 * * * *'   # каждые 2 минуты
  workflow_dispatch:

jobs:
  latency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run latency checker
        run: |
          python3 scripts/check_latency.py

      - name: Commit results
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add githubmirror/26_alive_final.txt

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Update 26_alive_final.txt"
            git push https://x-access-token:${GH_PAT}@github.com/Rusl2023/new-vpn-monitor.git HEAD:main
          fi

