name: Check VLESS Servers with Xray Checker

on:
  schedule:
    - cron: '*/2 * * * *'  # каждые 2 минуты
  workflow_dispatch:

jobs:
  check-xray:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Pull Docker image
      - name: Pull Xray Checker Docker image
        run: docker pull kutovoys/xray-checker:latest

      # 3. Run Xray Checker
      - name: Run Xray Checker
        run: |
          mkdir -p githubmirror/output
          echo "Starting Xray Checker..."
          docker run --rm \
            -v "${GITHUB_WORKSPACE}/githubmirror:/app/input_output" \
            kutovoys/xray-checker:latest \
            --input /app/input_output/26_alive_filtered.txt \
            --output /app/input_output/26_alive_final.txt \
            --timeout 1000 \
            --concurrent 50 \
            --ping

      # 4. Commit and push final alive servers
      - name: Commit 26_alive_final.txt
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add githubmirror/26_alive_final.txt

          if git diff --cached --quiet; then
              echo "No changes to commit"
          else
              git commit -m "Update 26_alive_final.txt"
              git push https://x-access-token:${GH_PAT}@github.com/Rusl2023/new-vpn-monitor.git HEAD:main
